local config = 
{
    {id = "intogame",need_amount = 1,catagory = 7,point = 1,},
    {id = "firsteat",need_amount = 1,catagory = 4,point = 1,},
    {id = "supereat",finish_type = "eat",need_amount = 100,catagory = 4,point = 2,award = "giftwrap_blueprint",},
    {id = "danding",finish_type = "eat", tag = "monsterlasagna_ai",need_amount = 10,catagory = 4,point = 2,},
    {id = "messiah",need_amount = 5,point = 3,},
    {id = "walkalot",finish_type = "periodic_task",special_condition = function(self,inst) return inst.components.locomotor.wantstomoveforward and not inst:HasTag("playerghost") end,need_amount = 18000,catagory = 7,point = 3,},
    {id = "stopalot",finish_type = "periodic_task",special_condition = function(self,inst) return not inst.components.locomotor.wantstomoveforward and not inst:HasTag("playerghost") end,need_amount = 5400,catagory = 7,point = 2,},
    {id = "tooyoung",finish_type = "death", attacker = {"flint","rocks","redgem","bluegem","goldnugget","nitre","cavein_boulder","marble"}, need_amount = 1,catagory = 10,point = 2,},
    {id = "evil",finish_type = "addfollower", follower = "mandrake_active",need_amount = 3,catagory = 6,point = 2,},
    {id = "snake",finish_type = "kill",victim = "tentacle",need_amount = 9,catagory = 2,point = 2,},
    {id = "deathalot",finish_type = "death",need_amount = 10,catagory = 10,point = 2,},
    {id = "deathfifty",finish_type = "death",need_amount = 50,point = 5,},
    {id = "nosanity",finish_type = "periodic_task",special_condition = function(self,inst,v) return inst.components.sanity.current < 1 and inst.components.health.currenthealth > 0 end,need_amount = 600,catagory = 7,point = 3,},
    {id = "sick",finish_type = "kill",victim = "glommer",need_amount = 1,catagory = 2,point = 2,},
    {id = "coldblood",finish_type = "kill",victim = "chester",need_amount = 1,catagory = 2,point = 2,},
    {id = "burn",need_amount = 1,catagory = 9,point = 1,},
    {id = "freeze",need_amount = 1,catagory = 9,point = 1,},
    {id = "pigmanfriend",finish_type = "addfollower", follower = "pigman", need_amount = 30,catagory = 9,point = 3,},
    {id = "brother",finish_type = "addfollower", follower = "bunnyman", need_amount = 30,catagory = 9,point = 3,},
    {id = "fishenthusiast",need_amount = 60,catagory = 8,point = 3,},
    {id = "pickenthusiast",finish_type = "picksomething",need_amount = 1000,catagory = 6,point = 3,},
    {id = "chopenthusiast",finish_type = "finishedwork",tag = "tree",need_amount = 500,catagory = 8,point = 3,},
    {id = "noob",finish_type = "death",cause = "NIL",need_amount = 1,catagory = 10,point = 1,},
    {id = "cookenthusiast",finish_type = "cook", need_amount = 100,catagory = 8,point = 3,},
    {id = "longage",finish_type = "periodic_task",special_condition = function(self,inst,v) 
        return inst.components.age:GetAgeInDays() - self[v.current] >= 1 end, need_amount = 70,catagory = 7,point = 5,},
    {id = "luck",need_amount = 1,catagory = 9,point = 10,},
    {id = "black",finish_type = "death",cause = "lightning",need_amount = 1,point = 7,},
    {id = "blackspat",finish_type = "kill",victim = "spat",special_condition = function(victim,inst) local single = true local pos = Vector3(victim.Transform:GetWorldPosition()) local ents = TheSim:FindEntities(pos.x,pos.y,pos.z, 40)  for k,v in pairs(ents) do if v:HasTag("player") and v ~= inst then single = false end end return single end, need_amount = 1,catagory = 2,point = 5,},
    {id = "buildenthusiast",finish_type = "consumeingredients",need_amount = 1000,catagory = 5,point = 5,},
    {id = "tank",need_amount = 3000,catagory = 2,point = 5,},
    {id = "angry",need_amount = 100000,catagory = 2,point = 5,},
    {id = "iceenthusiast",finish_type = "periodic_task",special_condition = function(self,inst) return inst.components.temperature.current <= 0 and inst.components.health.currenthealth > 0 end, need_amount = 600,catagory = 7,point = 5,},
    {id = "fireenthusiast",finish_type = "periodic_task",special_condition = function(self,inst) return inst.components.temperature.current >= 70 and inst.components.health.currenthealth > 0  end,need_amount = 600,catagory = 7,point = 5,},
    {id = "moist",finish_type = "periodic_task",special_condition = function(self,inst) return inst.components.moisture.moisture > 99.6 end,need_amount = 600,catagory = 7,point = 5,},
    {id = "a_yingguai",finish_type = "kill",victim = {"crawlinghorror","terrorbeak","crawlingnightmare","nightmarebeak"},need_amount = 50,catagory = 2,point = 1,},
    {id = "a_worm",finish_type = "kill",victim = "worm",need_amount = 25,catagory = 2,point = 2,},
    {id = "a_monkey",finish_type = "kill",victim = "monkey",need_amount = 15,catagory = 2,point = 1,},
    {id = "a_buzzard",finish_type = "kill",victim = "mossling",need_amount = 15,catagory = 2,point = 1,},
    {id = "a_lightninggoat",finish_type = "kill",victim = "lightninggoat",need_amount = 5,catagory = 2,point = 1,},
    {id = "a_spiderqueen",finish_type = "kill",victim = "spiderqueen",need_amount = 8,catagory = 2,point = 2,},
    {id = "a_spider",finish_type = "kill",victim = "spider",need_amount = 100,catagory = 2,point = 1,},
    {id = "a_spider_warrior",finish_type = "kill",victim = "spider_warrior",need_amount = 22,catagory = 2,point = 1,},
    {id = "a_spider_dropper",finish_type = "kill",victim = "spider_dropper",need_amount = 22,catagory = 2,point = 1,},
    {id = "a_spider_hider",finish_type = "kill",victim = "spider_hider",need_amount = 22,catagory = 2,point = 1,},
    {id = "a_spider_spitter",finish_type = "kill",victim = "spider_spitter",need_amount = 22,catagory = 2,point = 1,},
    {id = "a_warg",finish_type = "kill",victim = "warg",need_amount = 2,catagory = 2,point = 2,},
    {id = "a_hound",finish_type = "kill",victim = "hound",need_amount = 200,catagory = 2,point = 2,},
    {id = "a_firehound",finish_type = "kill",victim = "firehound",need_amount = 88,catagory = 2,point = 2,},
    {id = "a_icehound",finish_type = "kill",victim = "icehound",need_amount = 88,catagory = 2,point = 2,},
    {id = "a_koalefant_summer",finish_type = "kill",victim = "koalefant_summer",need_amount = 10,catagory = 2,point = 1,},
    {id = "a_koalefant_winter",finish_type = "kill",victim = "koalefant_winter",need_amount = 2,catagory = 2,point = 1,},
    {id = "a_catcoon",finish_type = "kill",victim = "catcoon",need_amount = 15,catagory = 2,point = 1,},
    {id = "a_bunnyman",finish_type = "kill",victim = "bunnyman",need_amount = 30,catagory = 2,point = 1,},
    {id = "a_leif",finish_type = "kill",victim =  {"leif","leif_sparse"},need_amount = 10,catagory = 2,point = 1,},
    {id = "a_slurtle",finish_type = "kill",victim = "slurtle",need_amount = 8,catagory = 2,point = 1,},
    {id = "a_tallbird",finish_type = "kill",victim = "tallbird",need_amount = 10,catagory = 2,point = 1,},
    {id = "a_walrus",finish_type = "kill",victim = "walrus",need_amount = 10,catagory = 2,point = 1,},
    {id = "a_bat",finish_type = "kill",victim = "bat",need_amount = 100,catagory = 2,point = 1,},
    {id = "a_butterfly",finish_type = "kill",victim = "butterfly",need_amount = 150,catagory = 2,point = 1,},
    {id = "a_killerbee",finish_type = "kill",victim = "killerbee",need_amount = 100,catagory = 2,point = 1,},
    {id = "a_deer",finish_type = "kill",victim = "deer",need_amount = 5,catagory = 2,point = 1,},
    {id = "a_mole",finish_type = "kill",victim = "mole",need_amount = 30,catagory = 2,point = 1,},
    {id = "a_mosquito",finish_type = "kill",victim = "mosquito",need_amount = 50,catagory = 2,point = 1,},
    {id = "a_penguin",finish_type = "kill",victim = "penguin",need_amount = 20,catagory = 2,point = 1,},
    {id = "a_merm",finish_type = "kill",victim = "merm",need_amount = 20,catagory = 2,point = 1,},
    {id = "a_frog",finish_type = "kill",victim = "frog",need_amount = 20,catagory = 2,point = 1,},
    {id = "a_beefalo",finish_type = "kill",victim = "beefalo",need_amount = 2,catagory = 2,point = 2,},
    {id = "a_perd",finish_type = "kill",victim = "perd",need_amount = 66,catagory = 2,point = 1,},
    {id = "a_krampus",finish_type = "kill",victim = "krampus",need_amount = 66,catagory = 2,point = 3,},
    {id = "a_robin_crow",finish_type = "kill",victim = "crow",need_amount = 30,catagory = 2,point = 1,},
    {id = "a_robin_robin",finish_type = "kill",victim =  "robin",need_amount = 30,catagory = 2,point = 1,},
    {id = "a_robin_winter",finish_type = "kill",victim =  "robin_winter",need_amount = 30,catagory = 2,point = 1,},
    {id = "a_robin_canary",finish_type = "kill",victim =  "canary",need_amount = 30,catagory = 2,point = 1,},
    {id = "a_pigman",finish_type = "kill",victim =  {"pigman","pigguard","moonpig"},need_amount = 44,catagory = 2,point = 1,},
    {id = "a_shadow_knight",finish_type = "kill",victim =  "shadow_knight",need_amount = 1,catagory = 3,point = 1,},
    {id = "a_shadow_bishop",finish_type = "kill",victim =  "shadow_bishop",need_amount = 1,catagory = 3,point = 1,},
    {id = "a_shadow_rook",finish_type = "kill",victim =  "shadow_rook",need_amount = 1,catagory = 3,point = 1,},
    {id = "a_moose",finish_type = "kill",victim =  "moose",need_amount = 1,catagory = 3,point = 3,},
    {id = "a_dragonfly",finish_type = "kill",victim =  "dragonfly",need_amount = 1,catagory = 3,point = 3,},
    {id = "a_bearger",finish_type = "kill",victim =  "bearger",need_amount = 1,catagory = 3,point = 3,},
    {id = "a_deerclops",finish_type = "kill",victim =  "deerclops",need_amount = 1,catagory = 3,point = 3,},
    {id = "a_stalker_forest",finish_type = "kill",victim =  "stalker_forest",need_amount = 1,catagory = 3,point = 1,},
    {id = "a_stalker",finish_type = "kill",victim =  "stalker",need_amount = 1,catagory = 3,point = 2,},
    {id = "a_stalker_atrium",finish_type = "kill",victim =  "stalker_atrium",need_amount = 1,catagory = 3,point = 3,},
    {id = "a_klaus",finish_type = "kill",victim =  "klaus",need_amount = 1,catagory = 3,point = 3,},
    {id = "a_antlion",finish_type = "kill",victim =  "antlion",need_amount = 1,catagory = 3,point = 3,},
    {id = "a_minotaur",finish_type = "kill",victim =  "minotaur",need_amount = 1,catagory = 3,point = 3,},
    {id = "a_beequeen",finish_type = "kill",victim =  "beequeen",need_amount = 1,catagory = 3,point = 5,},
    {id = "a_toadstool",finish_type = "kill",victim =  "toadstool",need_amount = 1,catagory = 3,point = 5,},
    {id = "a_toadstool_dark",finish_type = "kill",victim =  "toadstool_dark",need_amount = 1,catagory = 3,point = 10,},
    {id = "a_tallbirdegg",finish_type = "picksomething", pickitem = "tallbirdnest",need_amount = 6,catagory = 6,point = 1,},
    {id = "a_frogglebunwich",finish_type = "eat", tag = "frogglebunwich_ai",need_amount = 20,catagory = 4,point = 1,},
    {id = "a_baconeggs",finish_type = "eat", tag = "baconeggs_ai",need_amount = 80,catagory = 4,point = 1,},
    {id = "a_bonestew",finish_type = "eat", tag = "bonestew_ai",need_amount = 20,catagory = 4,point = 1,},
    {id = "a_fishtacos",finish_type = "eat", tag = "fishtacos_ai",need_amount = 10,catagory = 4,point = 1,},
    {id = "a_turkeydinner",finish_type = "eat", tag = "turkeydinner_ai",need_amount = 40,catagory = 4,point = 1,},
    {id = "a_fishsticks",finish_type = "eat", tag = "fishsticks_ai",need_amount = 40,catagory = 4,point = 1,},
    {id = "a_meatballs",finish_type = "eat", tag = "meatballs_ai",need_amount = 40,catagory = 4,point = 1,},
    {id = "a_perogies",finish_type = "eat", tag = "perogies_ai",need_amount = 120,catagory = 4,point = 1,},
    {id = "a_bisque",finish_type = "eat", tag = "hotchili_ai",need_amount = 22,point = 1,},
    {id = "a_surfnturf",finish_type = "eat", tag = "guacamole_ai",need_amount = 22,point = 1,},
    {id = "a_shark",finish_type = "kill",victim = "shark",catagory = 3,need_amount = 3,point = 2,},
    {id = "a_tigershark",finish_type = "kill",victim = "tigershark",need_amount = 1,point = 3,},
    {id = "a_twister",finish_type = "kill",victim = "twister",need_amount = 1,point = 3,},
    {id = "a_kraken",finish_type = "kill",victim = "kraken",need_amount = 1,point = 3,},
    {id = "a_snake",need_amount = 50,point = 1,},
    {id = "a_snake_poison",need_amount = 50,point = 1,},
    {id = "a_crocodog",need_amount = 250,point = 1,},
    {id = "a_poisoncrocodog",need_amount = 100,point = 1,},
    {id = "a_watercrocodog",need_amount = 100,point = 1,},
    {id = "a_1",need_amount = 2000,point = 3,},
    {id = "a_2",finish_type = "periodic_task", special_condition = function(self,inst,v) 
        return inst.components.age:GetAgeInDays() - self[v.current] >= 1 end,need_amount = 666,point = 4,},
    {id = "a_3",finish_type = "consumeingredients",need_amount = 3000,point = 4,},
    {id = "a_4",need_amount = 1000000,point = 4,},
    {id = "a_5",need_amount = 10000,point = 4,},
    {id = "a_6",need_amount = 20,finish_type = "eat", tag = "unagi_ai",need_amount = 6,catagory = 4,point = 1,},
    {id = "a_7",finish_type = "addfollower", follower = "rocky",need_amount = 10,catagory = 9,point = 1,},
    {id = "a_8",finish_type = "kill",victim = "birchnutdrake",need_amount = 30,catagory = 2,point = 1,},
    {id = "a_9",finish_type = "kill",victim = "hutch",need_amount = 1,catagory = 2,point = 1,},
    {id = "a_10",finish_type = "kill",victim = "rabbit",need_amount = 10,catagory = 2,point = 1,},
    {id = "a_11",finish_type = "kill",victim = "ghost",need_amount = 10,catagory = 2,point = 1,},
    {id = "a_12",finish_type = "kill",victim = "eyeplant",need_amount = 30,catagory = 2,point = 1,},
    {id = "a_13",finish_type = "eat", food = "icecream_ai",need_amount = 22,point = 1,},
    {id = "a_14",need_amount = 1,point = 1,},
    {id = "a_15",need_amount = 1,point = 1,},
    {id = "a_coffee",finish_type = "eat", food = "coffee",need_amount = 200,point = 1,},
    {id = "a_a1",finish_type = "eat",need_amount = 2000,point = 1,},
    {id = "a_a2",need_amount = 1, current_dont_reset = true,point = 5,},
    {id = "a_a3",need_amount = 1,current_dont_reset = true,point = 1,default_current = 1000},
    {id = "a_a4",need_amount = 1,current_dont_reset = true,point = 1,},
    {id = "a_a5",finish_type = "eat", tag = "honeyham_ai",need_amount = 80,catagory = 4,point = 1,},
    {id = "a_a6",finish_type = "kill",victim = {"knight","knight_nightmare"},need_amount = 5,catagory = 2,point = 1,},
    {id = "a_a7",finish_type = "kill",victim = {"bishop","bishop_nightmare"},need_amount = 5,catagory = 2,point = 1,},
    {id = "a_a8",finish_type = "kill",victim = {"rook","rook_nightmare"},need_amount = 5,catagory = 2,point = 1,},
    {id = "a_a9",finish_type = "kill",victim = "buzzard",need_amount = 6,catagory = 2,point = 1,},
    {id = "a_a10",finish_type = "kill",victim = "slurper",need_amount = 11,catagory = 2,point = 1,},
    {id = "a_a11",finish_type = "periodic_task", sub_finish_type = "equip",equip = "slurper",need_amount = 800,catagory = 7,point = 1,},
    {id = "a_a12",finish_type = "periodic_task", sub_finish_type = "equip",equip = "onemanband",need_amount = 800,catagory = 7,point = 1,},
    {id = "a_a13",finish_type = "builditem",builditem = "armormarble",need_amount = 15,catagory = 5,point = 1,},
    {id = "a_a14",finish_type = "builditem",builditem = "ruinshat",need_amount = 33,catagory = 5,point = 1,},
    {id = "a_a15",finish_type = "builditem",builditem = "armorruins",need_amount = 10,catagory = 5,point = 1,},
    {id = "a_a16",finish_type = "builditem",builditem = "ruins_bat",need_amount = 4,catagory = 5,point = 1,},
    {id = "a_a17",finish_type = "builditem",builditem = "gunpowder",need_amount = 80,catagory = 5,point = 1,},
    {id = "a_a18",finish_type = "builditem",builditem = "nightmarefuel",need_amount = 40,catagory = 5,point = 1,},
    {id = "a_a19",finish_type = "builditem",builditem = "pumpkin_lantern",need_amount = 6,catagory = 5,point = 1,},
    {id = "a_a20",finish_type = "builditem",builditem = "healingsalve",need_amount = 88,catagory = 5,point = 1,},
    {id = "a_a21",finish_type = "builditem",builditem = "bandage",need_amount = 40,catagory = 5,point = 1,},
    {id = "a_a22",finish_type = "picksomething", pickitem = {"cactus","oasis_cactus"},need_amount = 88,catagory = 6,point = 1,},
    {id = "a_a23",finish_type = "periodic_task", special_condition = function(self,inst) return inst.components.health.currenthealth > 0 and  inst.components.health.currenthealth < 2 end, need_amount = 1000,catagory = 7,point = 5,},
    {id = "a_a24",finish_type = "death",attacker = {"rabbit","mole",}, need_amount = 1,point = 1,},
    {id = "a_a25",finish_type = "cook", need_amount = 1000,point = 1,},
    {id = "a_a26",finish_type = "builditem",builditem = "blowdart_pipe",need_amount = 80,catagory = 5,point = 1,},
    {id = "a_a27",finish_type = "builditem",builditem = "blowdart_sleep",need_amount = 10,catagory = 5,point = 1,},
    {id = "a_a28",finish_type = "builditem",builditem = "blowdart_yellow",need_amount = 20,catagory = 5,point = 1,},
    {id = "a_a29",finish_type = "builditem",builditem = "blowdart_fire",need_amount = 10,catagory = 5,point = 1,},
    {id = "a_a30",finish_type = "builditem",builditem = "nightsword",need_amount = 30,catagory = 5,point = 1,},
    {id = "a_a31",finish_type = "builditem",builditem = "amulet",need_amount = 6,catagory = 5,point = 1,},
    {id = "a_a32",finish_type = "builditem",builditem = "panflute",need_amount = 1,catagory = 5,point = 1,},
    {id = "a_a33",finish_type = "deployitem",deployitem = {"pinecone","acorn","twiggy_nut", "jungletreeseed","coconut","teatree_nut","burr",},need_amount = 500,catagory = 8,point = 2,},
    {id = "a_a34",finish_type = "deployitem",deployitem = "butterfly",need_amount = 60,catagory = 8,point = 1,},
    {id = "a_a35",finish_type = "picksomething", pickitem = "red_mushroom",need_amount = 60,catagory = 6,point = 1,},
    {id = "a_a36",finish_type = "picksomething", pickitem = "blue_mushroom",need_amount = 60,catagory = 6,point = 1,},
    {id = "a_a37",finish_type = "picksomething", pickitem = "green_mushroom",need_amount = 60,catagory = 6,point = 1,},
    {id = "a_a38",finish_type = "builditem",builditem = "molehat",need_amount = 6,catagory = 5,point = 1,},
    {id = "a_a39",finish_type = "builditem",builditem = "lifeinjector",need_amount = 5,catagory = 5,point = 1,},
    {id = "a_a40",finish_type = "builditem",builditem = "bedroll_furry",need_amount = 6,catagory = 5,point = 1,},
    {id = "a_a41",finish_type = "builditem",builditem = "batbat",need_amount = 5,catagory = 5,point = 1,},
    {id = "a_a42",finish_type = "builditem",builditem = "deserthat",need_amount = 1,catagory = 5,point = 1,},
    {id = "a_a43",finish_type = "builditem",builditem = "rainhat",need_amount = 1,catagory = 5,point = 1,},
    {id = "a_a44",finish_type = "builditem",builditem = "staff_tornado",need_amount = 5,catagory = 5,point = 1,},
    {id = "a_a45",finish_type = "builditem",builditem = "nightstick",need_amount = 4,catagory = 5,point = 1,},
    {id = "a_a46",finish_type = "builditem",builditem = "yellowamulet",need_amount = 1,catagory = 5,point = 1,},
    {id = "a_a47",finish_type = "builditem",builditem = "multitool_axe_pickaxe",need_amount = 8,catagory = 5,point = 1,},
    {id = "a_a48",finish_type = "buildstructure", buildstructure = "mushroom_farm",need_amount = 5,catagory = 5,point = 1,},
    {id = "a_a49",finish_type = "buildstructure", buildstructure = "beebox",need_amount = 3,catagory = 5, point = 1,},
    {id = "a_a50",finish_type = "buildstructure", buildstructure = "endtable",need_amount = 9,catagory = 5,point = 1,},
    {id = "a_a51",finish_type = "buildstructure", buildstructure = "succulent_potted",need_amount = 6,catagory = 5,point = 1,},
    {id = "a_a52",finish_type = "buildstructure", buildstructure = "resurrectionstatue",need_amount = 1,catagory = 5,point = 1,},
    {id = "a_a53",finish_type = "builditem",builditem = "bernie_inactive",need_amount = 12,catagory = 5,point = 1,},
    {id = "a_a54",finish_type = "builditem",builditem = "sewing_tape",need_amount = 40,catagory = 5,point = 1,},
    {id = "a_a55",finish_type = "builditem",builditem = "book_brimstone",need_amount = 2,catagory = 5,point = 1,},
    {id = "a_a56",finish_type = "builditem",builditem = "wathgrithrhat",need_amount = 40,catagory = 5,point = 1,},
    {id = "a_a57",finish_type = "picksomething", pickitem = {"flower_cave","flower_cave_double","flower_cave_triple"},need_amount = 80,catagory = 6,point = 1,},
    {id = "a_a58",finish_type = "eat", tag = "dragonpie_ai",need_amount = 20,catagory = 4,point = 1,},
    {id = "a_a59",finish_type = "eat", tag = "flowersalad_ai",need_amount = 40,catagory = 4,point = 1,},
    {id = "a_a60",finish_type = "eat", food = "meat_dried",need_amount = 40,catagory = 4,point = 1,},
    {id = "a_a61",finish_type = "builditem",builditem = "thulecite",need_amount = 20,catagory = 5,point = 1,},
    {id = "a_a62",finish_type = "builditem",builditem = "greenamulet",need_amount = 4,catagory = 5,point = 1,},
    {id = "a_a63",finish_type = "builditem",builditem = "yellowstaff",need_amount = 2,catagory = 5,point = 1,},
    {id = "a_a64",finish_type = "eat", tag = "jellybean_ai",need_amount = 40,catagory = 4,point = 1,},
    {id = "a_a65",finish_type = "give",target = "pigking",need_amount = 120,catagory = 8,point = 1,},
    {id = "a_a66",finish_type = "give",target = "birdcage",need_amount = 120,catagory = 8,point = 1,},
    {id = "a_a67",finish_type = "builditem",builditem = "hambat",need_amount = 1,catagory = 5,point = 1,},
    {id = "a_a68",finish_type = "builditem",builditem = "footballhat",need_amount = 10,catagory = 5,point = 1,},
    {id = "a_a69",finish_type = "builditem",builditem = "armorwood",need_amount = 10,catagory = 5,point = 1,},
    {id = "a_a70", pickitem = "tumbleweed",need_amount = 66,catagory = 6,point = 1,},
    {id = "a_a71",finish_type = "finishedwork",tag = "boulder",need_amount = 60,catagory = 8,point = 1,},
    {id = "a_a72",finish_type = "finishedwork",tag = "frozen",need_amount = 30,catagory = 8,point = 1,},
    {id = "moon_01",finish_type = "periodic_task", sub_finish_type = "equip",equip = "armorslurper",need_amount = 1000,catagory = 7,point = 1,},
    {id = "moon_02",finish_type = "builditem",builditem = "miniflare",need_amount = 12,catagory = 5,point = 1,},
    {id = "moon_03",finish_type = "builditem",builditem = "mast_item",need_amount = 1,catagory = 5,point = 1,},
    {id = "moon_04",finish_type = "builditem",builditem = "oar_driftwood",need_amount = 1,catagory = 5,point = 1,},
    {id = "moon_05",finish_type = "builditem",builditem = "glasscutter",need_amount = 6,catagory = 5,point = 1,},
    {id = "moon_06",finish_type = "deployitem",deployitem = "rock_avocado_fruit_sprout",need_amount = 1,catagory = 8,point = 1,},
    {id = "moon_07",finish_type = "kill",victim = "puffin",need_amount = 30,catagory = 2,point = 1,},
    {id = "moon_08",finish_type = "kill",victim = "spider_moon",need_amount = 22,catagory = 2,point = 1,},
    {id = "moon_09",finish_type = "deployitem",deployitem = "moonbutterfly",need_amount = 40,catagory = 8,point = 1,},
    {id = "moon_10",finish_type = "picksomething", pickitem = "rock_avocado_bush",need_amount = 80,catagory = 6,point = 1,},
    {id = "moon_11",finish_type = "kill",victim = "smallbird",need_amount = 1,catagory = 2,point = 1,},
    {id = "moon_12",finish_type = "kill",victim = "babybeefalo",need_amount = 1,catagory = 2,point = 1,},
    {id = "moon_13",need_amount = 40,point = 1,},
    {id = "moon_14",finish_type = "eat", food = {"drumstick_cooked", "eel_cooked", "fish_cooked", "cookedmeat", "cookedsmallmeat"},need_amount = 40,catagory = 4,point = 1,},
    {id = "moon_15",finish_type = "eat", tag = "taffy_ai",need_amount = 40,catagory = 4,point = 1,},
    {id = "moon_16",finish_type = "periodic_task", sub_finish_type = "equip",equip = "flowerhat",need_amount = 960,catagory = 7,point = 1,},
    {id = "moon_17",finish_type = "cook",product = "wetgoop",need_amount = 10,catagory = 8,point = 1,},
    {id = "moon_18",finish_type = "kill",victim = {"spiderden","spiderden_2","spiderden_3"},special_condition = function(victim) return victim.components.upgradeable and not victim.components.upgradeable:CanUpgrade() end,need_amount = 6,catagory = 9,point = 1,},
    {id = "moon_19",finish_type = "picksomething", pickitem = "cave_banana_tree",need_amount = 40,catagory = 6,point = 1,},
    {id = "moon_20",finish_type = "picksomething", pickitem = "wormlight_plant",need_amount = 40,catagory = 6,point = 1,},
    {id = "moon_21",finish_type = "finishedwork",prefab = {"ruins_statue_head","ruins_statue_head_nogem","ruins_statue_mage","ruins_statue_mage_nogem"},need_amount = 30,catagory = 8,point = 1,},
    {id = "moon_22",finish_type = "kill",victim = "tentacle_pillar",need_amount = 9,catagory = 2,point = 1,},
    {id = "moon_23",finish_type = "kill",victim = "tentacle_pillar_arm",need_amount = 30,catagory = 2,point = 1,},
    {id = "moon_24",finish_type = "kill",victim = "malbatross",need_amount = 1,catagory = 3,point = 3,},
    {id = "moon_25",finish_type = "kill",victim = {"pigman","pigguard","moonpig"},special_condition = function() return TheWorld.components.worldstate.data.isfullmoon end, need_amount = 20,catagory = 2,point = 1,},
    {id = "moon_26",finish_type = "deployitem",deployitem = "marblebean",need_amount = 40,catagory = 8,point = 1,},
    {id = "moon_27",finish_type = "periodic_task", sub_finish_type = "equip",equip = "armorsnurtleshell",need_amount = 2400,catagory = 7,point = 1,},
    {id = "moon_28",finish_type = "death",attacker = "boomerang", need_amount = 1,catagory = 10,point = 1,},
    {id = "moon_29",finish_type = "periodic_task", sub_finish_type = "equip",equip = "bushhat",need_amount = 2400,catagory = 7,point = 1,},
    {id = "moon_30",need_amount = 60,catagory = 7,point = 1,},
    {id = "moon_31",finish_type = "periodic_task", special_condition = function(self,inst) return inst.replica and inst.replica.inventory and inst.replica.inventory:Has("moonrockseed",1) end,need_amount = 2400,catagory = 7,point = 1,},
    {id = "moon_32",finish_type = "periodic_task",special_condition = function(self,inst,v)  local check_equipslots = true for k,v in pairs(inst.components.inventory.equipslots) do if v  then  check_equipslots = false break end end return check_equipslots end, need_amount = 1500,catagory = 7,point = 2,},
    {id = "moon_33",need_amount = 2400,catagory = 7,point = 1,},
    {id = "moon_34",finish_type = "working",target = "rock_avocado_fruit",need_amount = 100,catagory = 8,point = 1,},
    {id = "moon_35",need_amount = 10,catagory = 9,point = 1,},
    {id = "moon_36",need_amount = 10,catagory = 9,point = 1,},
    {id = "moon_37",finish_type = "cook",product = "waffles",need_amount = 3,catagory = 8,point = 1,},
    {id = "moon_38",finish_type = "cook",product = "monsterlasagna",need_amount = 10,catagory = 8,point = 1,},
    {id = "moon_39",finish_type = "cook",product = "bananapop",need_amount = 10,catagory = 8,point = 1,},
    {id = "moon_40",finish_type = "cook",product = "bonesoup",need_amount = 2,catagory = 8,point = 1,},
    {id = "moon_41",finish_type = "cook",product = "voltgoatjelly",need_amount = 5,catagory = 8,point = 1,},
    {id = "moon_42",finish_type = "eat", food = "gears",need_amount = 60,catagory = 9,point = 1,},
    {id = "moon_43",finish_type = "picksomething", pickitem = "reeds", need_amount = 80,catagory = 6,point = 1,},
    {id = "moon_44",finish_type = "working",tag = "moonglass",special_condition = function(data) return data.target.components.workable.workleft < 1  end, need_amount = 20,catagory = 8,point = 1,},
    {id = "moon_45",finish_type = "deployitem",deployitem = "dug_trap_starfish",need_amount = 10,catagory = 8,point = 1,},
    {id = "moon_46", pickitem = {"carrat_planted","carrat"},need_amount = 10,catagory = 6,point = 1,},
    {id = "moon_47",need_amount = 8,catagory = 8,point = 1,},
    {id = "moon_48",need_amount = 1,catagory = 8,point = 1,},
    {id = "moon_49",need_amount = 10,catagory = 8,point = 1,},
    {id = "moon_50",finish_type = "periodic_task",sub_finish_type = "consume", item = "purplegem", need_amount = 40,catagory = 9,point = 4,},
    {id = "moon_51",need_amount = 1,catagory = 9,point = 1,},
    {id = "moon_52",finish_type = "kill",victim = "squid",need_amount = 5,catagory = 2,point = 1,},
    {id = "moon_53",finish_type = "eat", tag = "seafoodgumbo_ai",need_amount = 20,catagory = 4,point = 1,},
    {id = "moon_54",finish_type = "eat", tag = "surfnturf_ai",need_amount = 20,catagory = 4,point = 1,},
    {id = "moon_55",finish_type = "eat", tag = "californiaroll_ai",need_amount = 20,catagory = 4,point = 1,},
    {id = "moon_56",need_amount = 1,point = 1,},
    {id = "moon_57",finish_type = "kill",victim = "fruitdragon",need_amount = 3,point = 1,},
    {id = "moon_58",finish_type = "builditem",builditem = "trap_teeth",need_amount = 88,catagory = 5,point = 1,},
    {id = "moon_59",need_amount = 1,point = 1,},
    {id = "moon_60",need_amount = 1,point = 1,},
    {id = "seas_01",finish_type = "periodic_task",sub_finish_type = "consume", item = "spore_medium",need_amount = 40,catagory = 9,point = 1,},
    {id = "seas_02",finish_type = "periodic_task",sub_finish_type = "consume", item = "spore_small",need_amount = 40,catagory = 9,point = 1,},
    {id = "seas_03",finish_type = "periodic_task",sub_finish_type = "consume", item = "spore_tall",need_amount = 40,catagory = 9,point = 1,},
    {id = "seas_04",finish_type = "periodic_task", special_condition = function(self,inst) return inst.sg:HasStateTag("sleeping") end,need_amount = 1000,catagory = 7,point = 1,},
    {id = "seas_05",finish_type = "death",cause = {"red_cap","green_cap_cooked","blue_cap_cooked","spoiled_food","durian","rottenegg","cactus_meat","potato","pepper","monstermeat","cookedmonstermeat","monstermeat_dried","mashedpotatoes"   ,"mashedpotatoes_spice_chili","mashedpotatoes_spice_sugar","mashedpotatoes_spice_garlic","mashedpotatoes_spice_salt","dragonchilisalad" ,"dragonchilisalad_spice_chili","dragonchilisalad_spice_sugar","dragonchilisalad_spice_garlic","dragonchilisalad_spice_salt" ,"powcake","powcake_spice_chili" ,"powcake_spice_sugar","powcake_spice_garlic","powcake_spice_salt","taffy"  ,"taffy_spice_chili"   ,"taffy_spice_sugar"  ,"taffy_spice_garlic"  ,"taffy_spice_salt" ,"monsterlasagna"   ,"monsterlasagna_spice_chili"    ,"monsterlasagna_spice_sugar"   ,"monsterlasagna_spice_garlic","monsterlasagna_spice_salt",}, need_amount = 1,catagory = 10,point = 1,},
    {id = "seas_06",need_amount = 20,catagory = 9,point = 1,},
    {id = "seas_07",finish_type = "picksomething", pickitem = "flower", animname = "rose",need_amount = 2,catagory = 6,point = 1,},
    {id = "seas_08",finish_type = "addfollower", follower = "catcoon",need_amount = 10,catagory = 9,point = 1,},
    {id = "seas_09",finish_type = "addfollower", follower = {"spider_hider","spider_spitter","spider","spider_warrior","spider_dropper",},need_amount = 30,catagory = 9,point = 1,},
    {id = "seas_10",finish_type = "kill",victim = "rocky",need_amount = 1,catagory = 2,point = 1,},
    {id = "seas_11",finish_type = "give", target = "pigman", item = "green_mushroomhat",need_amount = 1,catagory = 9,point = 1,},
    {id = "seas_12",finish_type = "give", target = "antlion", need_amount = 10,catagory = 8,point = 1,},
    {id = "seas_13",need_amount = 20,catagory = 9,point = 1,},
    {id = "seas_14",finish_type = "periodic_task",special_condition = function(self,inst) return inst.replica.rider ~= nil and inst.replica.rider:IsRiding() end, need_amount = 2400,catagory = 7,point = 1,},
    {id = "seas_15",finish_type = "periodic_task",sub_finish_type = "consume", item = {"redmooneye","bluemooneye","purplemooneye","greenmooneye","orangemooneye","yellowmooneye",}, need_amount = 1,catagory = 9,point = 1,},
    {id = "seas_16",finish_type = "kill",victim = "crabking",need_amount = 1,catagory = 3,point = 6,},
    {id = "seas_17",finish_type = "eat", tag = "lobsterbisque_ai",need_amount = 6,catagory = 4,point = 1,},
    {id = "seas_18",finish_type = "eat",tag = "lobsterdinner_ai",need_amount = 2,catagory = 4,point = 1,},
    {id = "seas_19",finish_type = "builditem",builditem = "trident",need_amount = 1,catagory = 5,point = 1,},
    {id = "seas_20",finish_type = "builditem",builditem = "reskin_tool",need_amount = 1,catagory = 5,point = 1,},
    {id = "boss_01",finish_type = "kill",victim = "moose",need_amount = {5,8,},point = 1,},
    {id = "boss_02",finish_type = "kill",victim = "antlion",need_amount = {3,5,8,},point = 1,},
    {id = "boss_03",finish_type = "kill",victim = "bearger",need_amount = {3,5,8,},point = 1,},
    {id = "boss_04",finish_type = "kill",victim = "deerclops",need_amount = {3,5,8,},point = 1,},
    {id = "boss_05",finish_type = "kill",victim = "dragonfly",need_amount = {5,8,},point = 1,},
    {id = "boss_06",finish_type = "kill",victim = "beequeen",need_amount = {5,8,},point = 1,},
    {id = "boss_07",finish_type = "kill",victim = "klaus",need_amount = {3,5,8,},point = 1,},
    {id = "boss_08",finish_type = "kill",victim = "toadstool",need_amount = {3,5,8,},point = 1,},
    {id = "boss_09",finish_type = "kill",victim = "toadstool_dark",need_amount = {3,5,8,},point = 1,},
    {id = "boss_10",finish_type = "kill",victim = "minotaur",need_amount = {1},point = 1,},
    {id = "boss_11",finish_type = "kill",victim = "stalker_atrium",need_amount = {3,5,8,},point = 1,},
    {id = "boss_12",finish_type = "kill",victim = "spiderqueen",need_amount = {15},point = 1,},
    {id = "boss_13",finish_type = "kill",victim = {"leif","leif_sparse"},need_amount = {20},point = 1,},
    {id = "boss_14",finish_type = "kill",victim = {"koalefant_summer","koalefant_winter","warg","spat"},need_amount = {20},point = 1,},
    {id = "boss_15",finish_type = "kill",victim = {"knight","bishop","knight_nightmare","bishop_nightmare","rook","rook_nightmare",},need_amount = {25,},point = 1,},
    {id = "boss_16",finish_type = "kill",victim = "tallbird",need_amount = {30,},point = 1,},
    {id = "boss_17",finish_type = "kill",victim = "worm",need_amount = {35,},point = 1,},
    {id = "boss_18",finish_type = "kill",victim = "crabking",need_amount = {3},point = 1,},
    {id = "boss_19",finish_type = "kill",victim = "malbatross",need_amount = {3,},point = 1,},
    {id = "boss_20",finish_type = "finishedwork",prefab = "mound",need_amount = 20,point = 1,},
    {id = "boss_21",finish_type = "kill",victim = "lordfruitfly",need_amount = {3,5,8},point = 1,},
    {id = "boss_22",finish_type = "kill",victim = "alterguardian_phase1",need_amount = {3,},point = 1,},
    {id = "boss_23",finish_type = "kill",victim = "alterguardian_phase2",need_amount = {3,},point = 1,},
    {id = "boss_24",finish_type = "kill",victim = "alterguardian_phase3",need_amount = {3,},point = 1,},
    {id = "boss_25",finish_type = "kill",victim = "eyeofterror",need_amount = {3,},point = 1,},
    {id = "boss_26",finish_type = "kill",victim = "twinofterror1",need_amount = {3,},point = 1,},
    {id = "boss_27",finish_type = "kill",victim = "twinofterror2",need_amount = {3,},point = 1,},

    {id = "killbyrose",finish_type = "death",cause = "flower",catagory = 10, need_amount = 1,point = 1,},
    {id = "eatleafymeatsouffle",finish_type = "eat",food = "leafymeatsouffle",catagory = 4, need_amount = 10,point = 1,},
    {id = "reviveamulet",catagory = 9, need_amount = 5,point = 1,},
    {id = "getbathbomb",finish_type = "periodic_task",sub_finish_type = "hold", item = "bathbomb",need_amount = 10,catagory = 9,point = 1,},
    {id = "killshadowknight3",finish_type = "kill",victim = "shadow_knight",special_condition = function(victim) return victim.level == 3 end,need_amount = 1,catagory = 3,point = 1,},
    {id = "killshadowbishop3",finish_type = "kill",victim = "shadow_bishop",special_condition = function(victim) return victim.level == 3 end,need_amount = 1,catagory = 3,point = 1,},
    {id = "killshadowrook3",finish_type = "kill",victim = "shadow_rook",special_condition = function(victim) return victim.level == 3 end,need_amount = 1,catagory = 3,point = 1,},
    {id = "starvedeath",finish_type = "death",cause = "hunger",catagory = 10,need_amount = 1,point = 1,},

    {id = "killlordfruitfly",finish_type = "kill",victim = "lordfruitfly",need_amount = 1,catagory = 3,point = 1,},
    {id = "killalterguardian_phase1",finish_type = "kill",victim = "alterguardian_phase1",need_amount = 1,catagory = 3,point = 2,},
    {id = "killalterguardian_phase2",finish_type = "kill",victim = "alterguardian_phase2",need_amount = 1,catagory = 3,point = 3,},
    {id = "killalterguardian_phase3",finish_type = "kill",victim = "alterguardian_phase3",need_amount = 1,catagory = 3,point = 4,},
    {id = "killeyeofterror",finish_type = "kill",victim = "eyeofterror",need_amount = 1,catagory = 3,point = 2,},
    {id = "killtwinofterror1",finish_type = "kill",victim = "twinofterror1",need_amount = 1,catagory = 3,point = 3,},
    {id = "killtwinofterror2",finish_type = "kill",victim = "twinofterror2",need_amount = 1,catagory = 3,point = 4,},

    {id = "all",need_amount = 1,catagory = 9,point = 10,},
}


local specific_ignore = 
{
    ["wormwood"] = 
    {
         "checkseas_05", 
    },
    ["wurt"] =  
    {
        "checka_a5","checka_6","checkdanding","checka_frogglebunwich","checka_baconeggs","checka_bonestew","leafymeatsouffle",
        "checka_fishtacos","checka_turkeydinner","checka_fishsticks","checka_meatballs","checka_perogies",
        "checka_a60","checkmoon_14","checkmoon_53","checkmoon_54","checkmoon_55","checkseas_17","checkseas_18", 
    },
    ["willow"] = 
    {
         
    },
    ["winona"] = 
    {
         
    },
    ["wickerbottom"] = 
    {
        "checkseas_04", 
    },
    ["wathgrithr"] = 
    {
       "checka_a59", "checka_a58",
    },
    ["warly"] = 
    {
        "checka_a60","checkmoon_14",
    },
    ["yangjian"] = 
    {
        "checkseas_20","checka_a30","checka_a31","checka_a32","checka_a41","checka_a52", "checknosanity",
    },
    ["pigsy"] =
    {
        "checka_a52",
    }
}

local specific_achievement = 
{
    ["winona"] = {"checka_a54",},
    ["willow"] = {"checka_a53",},
    ["wickerbottom"] = {"checka_a55", },
    ["wathgrithr"] = {"checka_a56",},
    ["warly"] = {"checkmoon_40","checkmoon_41",},
    ["wx78"] = {"checkmoon_42",},
}


local achievement_config_id2value = {}
local category_config = {}
local modname = KnownModIndex:GetModActualName("New Achivement")
local need_amount_ratio  = GetModConfigData("coindifficulty",modname)
local function PretreatmentAchievementConfig()
    for _,v in pairs(config) do
        -- v.need_amount = 1
        v.check = "check" .. v.id
        v.current = "current" .. v.id .. "amount"
        if type(v.need_amount) == "number" then 
            v.need_amount = math.ceil(v.need_amount * need_amount_ratio)
        end
        achievement_config_id2value[v.id] = v
        if v.finish_type then
            if not category_config[v.finish_type] then
                category_config[v.finish_type] = {}
                table.insert(category_config[v.finish_type], v)
            else
                table.insert(category_config[v.finish_type], v)
            end
        end
    end
end
PretreatmentAchievementConfig()

local achievement_config = 
{
    config = config,
    idconfig = achievement_config_id2value,
    specific_ignore = specific_ignore,
    specific_achievement = specific_achievement,
    category_config = category_config,
}

return achievement_config